AllCops:
  RunRailsCops: true

  DisplayCopNames: true
  DisplayStyleGuide: true

  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'log/**/*'

Style/GuardClause:
  MinBodyLength: 3

Metrics/LineLength:
  Max: 115
  AllowURI: true

inherit_from: .rubocop_todo.yml
