export const CHANGE_AUTO_PLAY = 'TOGGLE_AUTO_PLAY';
export const CHANGE_NUMBER_FORMAT = 'CHANGE_NUMBER_FORMAT';
export const CHANGE_RATE_FORMAT = 'CHANGE_RATE_FORMAT';
export const CHANGE_PROGRESS_SLIDERS = 'CHANGE_PROGRESS_SLIDERS';
